### ISSUE TITLE
Error in example documentation

### ISSUE THREAD

**Issue by albertovilla** [oasis-roles/passwordless_ssh#7]
Hi, in the example playbook you have the following:

`passwordless_ssh_user_dir: /home/testuser`

I think it should be:

`passwordless_ssh_user_home: /home/testuser`

**Comment by tehsmyers** [comment]
It definitely looks that way, thanks for the issue.

**Comment by tehsmyers** [comment]
So I fixed this, but forgot to close the issue with the commit. Woops!
